- name: Update apt package index
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install required packages for Docker
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for Docker's official GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash

- name: Update apt package index after adding Docker repository
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Amazon ECR Credential Helper
  apt:
    name: amazon-ecr-credential-helper
    state: present

- name: Create Docker config directory
  file:
    path: /root/.docker
    state: directory
    mode: '0755'

- name: Configure Docker to use Amazon ECR Credential Helper
  copy:
    dest: /root/.docker/config.json
    content: |
      {
        "credHelpers": {
          "160885287796.dkr.ecr.ap-northeast-2.amazonaws.com": "ecr-login"
        }
      }
    mode: '0644'

- name: Verify Amazon ECR Credential Helper installation
  shell: which docker-credential-ecr-login
  register: ecr_helper_path
  changed_when: false

- debug:
    msg: "Amazon ECR Credential Helper installed at {{ ecr_helper_path.stdout }}"