apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dododocs-cluster
  region: ap-northeast-2

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

vpc:
  id: vpc-0a2d2976d26679a81
  subnets:
    public:
      ap-northeast-2a:
        id: subnet-07cad42a01fd0a504
      ap-northeast-2c:
        id: subnet-0acd4352067ac9860
    private:
      ap-northeast-2a:
        id: subnet-049f8707431c60154
      ap-northeast-2c:
        id: subnet-0d21d7798093afc53

managedNodeGroups:
  - name: doodocs-node-group
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    iam:
      instanceRoleARN: arn:aws:iam::730335509885:role/eks-node-role
    privateNetworking: true
    labels:
      role: worker
    tags:
      nodegroup-role: worker
