apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - infra-ingress.yaml


configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf=nginx.conf

generatorOptions:
  disableNameSuffixHash: true
