apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
          - rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/custom.conf
            subPath: custom.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
