apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-deploy
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'nginx-role'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-database-config: 'infra/nginx-config'
        vault.hashicorp.com/agent-inject-template-nginx-config: |
          {{ with secret "infra/nginx-config" -}}
            export ALLOWED_IP="{{ .Data.data.ALLOWED_IP }}"
          {{- end }}
    spec:
      serviceAccountName: nginx-sa
      containers:
      - name: nginx
        image: nginx:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            . /vault/secrets/nginx-config
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
            
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items:
              - key: dododocs-nginx.conf
                path: nginx.conf

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  namespace: infra