apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fe-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fe-deploy
    spec:
      containers:
      - name: fe-app
        image: hyesushim/dododocs-fe:latest
        ports:
            - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: react-app-config
              key: REACT_APP_API_BASE_URL
