apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fe-deploy
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP