apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
- fe-deployment.yaml
- fe-service.yaml
# - fe-ingress.yaml
images:
- name: hyesushim/dododocs-fe
  newTag: c8b9dee
configMapGenerator:
- name: fe-config
  literals:
  - REACT_APP_API_BASE_URL=/
generatorOptions:
  disableNameSuffixHash: true
