apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
- fe-deployment.yaml
- fe-service.yaml
- fe-ingress.yaml
images:
- name: hyesushim/dododocs-fe
  newTag: d5c676f
configMapGenerator:
- name: fe-config
  literals:
  - REACT_APP_API_BASE_URL=http://be-service.backend.svc.cluster.local
generatorOptions:
  disableNameSuffixHash: true
