apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend

resources:
  - fe-deployment.yaml
  - fe-service.yaml
  - fe-ingress.yaml

images:
  - name: hyesushim/dododocs-fe
    newTag: sha256:50a3b7309527d3c923ee2e514a71580305545121ad68710979a1d051226230d9

configMapGenerator:
  - name: fe-config
    literals:
      - REACT_APP_API_BASE_URL=http://be-service.backend.svc.cluster.local

generatorOptions:
  disableNameSuffixHash: true
