apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: be_image=hyesushim/dododocs-be
    argocd-image-updater.argoproj.io/be_image.update-strategy: newest-build
    argocd-image-updater.argoproj.io/be_image.tag-pattern: "^[a-f0-9]{7}$" 
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: dododocs
  source:
    repoURL: https://github.com/DoDoDocs/dododocs-cloud.git
    targetRevision: main
    path: ./BE
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true