apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai
  namespace: myargocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: hyeushim/dododocs-ai
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  project: dododocs
  source:
    repoURL: https://github.com/DoDoDocs/dododocs-cloud.git
    targetRevision: develop
    path: ./AI
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true