apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deploy
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-deploy
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'ai-role'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-database-config: 'ai/prod'
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{ with secret "ai/prod" }}
          {{- range $key, $value := .Data.data }}
            export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end }}
    spec:
      serviceAccountName: ai-efs-sa
      containers:
      - name: ai-app
        image: hyesushim/dododocs-ai:latest
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            . /vault/secrets/database-config
            env > /vault/secrets/test
            env
            exec python lambda_chat.py
        ports:
          - containerPort: 5001
        volumeMounts: 
          - name: efs-storage
            mountPath: /mnt/chroma_DB
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-claim 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: ai

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc