kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0ddf6dc34bb06349c::fsap-06637761fdd9a4b18
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deploy
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-deploy
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'ai-role'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-database-config: 'ai/prod'
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{ with secret "ai/prod" }}
          {{- range $key, $value := .Data.data }}
            export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end }}
    spec:
      serviceAccountName: ai-sa
      containers:
      - name: ai-app
        image: hyesushim/dododocs-ai:latest
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            . /vault/secrets/database-config
            env > /vault/secrets/test
            env
            exec python lambda_chat.py
        ports:
          - containerPort: 5001
        volumeMounts: 
          - name: efs-volume
            mountPath: /mnt/chroma_DB
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: efs-claim
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: ai
