apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deploy
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-deploy
    spec:
      containers:
      - name: ai-app
        image: hyesushim/dododocs-ai:latest
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: ai-secret-volume
            mountPath: /etc/secrets
            readOnly: true
      volumes:
      - name: ai-secret-volume
        secret:
          secretName: ai-secret
