apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deploy
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-deploy
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'ai-role'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-database-config: 'ai/prod'
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{ with secret "ai/prod" }}
          {{- range $key, $value := .Data.data }}
            export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end }}
    spec:
      serviceAccountName: ai-sa
      containers:
      - name: ai-app
        image: hyesushim/dododocs-ai:latest
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            . /vault/secrets/database-config
            env > /vault/secrets/test
            env
            exec uvicorn ktb_server:app --host 0.0.0.0 --port 8000 --log-level debug --timeout-keep-alive 180
        ports:
          - containerPort: 8000
---
apiVersion: apps/v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: ai