apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: ai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
