apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim1
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc