apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - ai-deployment.yaml
  - ai-service.yaml

images:
  - name: hyesushim/dododocs-ai
    newTag: sha256:4487c28081ad6a3c381040373cf181565d9df18c42c64886d408f129d7068a72

