apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: efs-
  storageClassName: efs-sc
