apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: myargocd
spec:
  project: dododocs
  source:
    repoURL: https://github.com/DoDoDocs/dododocs-cloud.git
    targetRevision: develop
    path: ./BE
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true