apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deploy
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: be-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: be-deploy
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'backend-role'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-database-config: 'backend/prod'
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{ with secret "backend/prod" }}
          {{- range $key, $value := .Data.data }}
            export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end }}
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: be-app
        image: hyesushim/dododocs-be:latest
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            . /vault/secrets/database-config
            env > /vault/secrets/test
            env
            exec java -jar -Dspring.profiles.active=prod /home/gradle/project/build/libs/dododocs-0.0.1-SNAPSHOT.jar
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: be-config 
        - secretRef:
            name: be-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: backend