apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deploy
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: be-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: be-deploy
    spec:
      containers:
      - name: be-app
        image: hyesushim/dododocs-be:latest
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: be-config 
        - secretRef:
            name: be-secret
