apiVersion: v1
kind: Service
metadata:
  name: be-service
  namespace: default
spec:
  type: ClusterIP 
  selector:
    app.kubernetes.io/name: be-deploy  
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 8080   
