apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
- be-deployment.yaml
- be-service.yaml
# - be-ingress.yaml
images:
- name: hyesushim/dododocs-be
  newTag: 7fb1ee1
configMapGenerator:
- name: be-config
  literals:
  - AUTHORIZE_URI=https://github.com/login/oauth/authorize
  - AWS_REGION=ap-northeast-2
  - DATABASE_TO_UPPER="FALSE"
  - DB_CLOSE_DELAY="-1"
  - DB_CLOSE_ON_EXIT="FALSE"
  - MODE=MYSQL
  - REDIRECT_URI=https://dododocs.com/callback/github
  # - REDIRECT_URI=http://localhost:3000/callback/github
  - TOKEN_URL=https://github.com/login/oauth/access_token
  - USER_URI=https://api.github.com/user
  # - AI_BASIC_URL=http://ai.dododocs.com
  - AI_BASIC_URL=http://ai-service.ai.svc.cluster.local
generatorOptions:
  disableNameSuffixHash: true
