apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
  - be-deployment.yaml
  - be-service.yaml

images:
  - name: hyesushim/dododocs-be
    digest: sha256:c7efebbd1e71727d888e0d0d62abbc40dd532900b2551b622cd45585892f9d29

configMapGenerator:
  - name: be-config
    literals:
      - AUTHORIZE_URI=https://github.com/login/oauth/authorize
      - AWS_REGION=ap-northeast-2
      - DATABASE_TO_UPPER="FALSE"
      - DB_CLOSE_DELAY="-1"
      - DB_CLOSE_ON_EXIT="FALSE"
      - MODE=MYSQL
      - REDIRECT_URI=http://dododocs.com/callback/github
      - TOKEN_URL=https://github.com/login/oauth/access_token
      - USER_URI=https://api.github.com/user
      - AI_BASIC_URL=http://ai-service.ai.svc.cluster.local


generatorOptions:
  disableNameSuffixHash: true
