- name: Check system architecture
  command: uname -m
  register: system_arch
  changed_when: false

- name: Set CloudWatch Agent download URL based on architecture
  set_fact:
    cwagent_url: >-
      {{ "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
      if system_arch.stdout == "x86_64" else
      "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb" }}

- name: Download CloudWatch Agent installer
  get_url:
    url: "{{ cwagent_url }}"
    dest: ./amazon-cloudwatch-agent.deb
    mode: '0644'

- name: Install CloudWatch Agent
  shell: sudo dpkg -i -E ./amazon-cloudwatch-agent.deb

- name: Copy config file
  template:
    src: ../files/cloudwatchagent.json
    dest: /home/ubuntu/config.json

- name: Move config
  shell: sudo mv /home/ubuntu/config.json /opt/aws/amazon-cloudwatch-agent/etc

- name: Add CloudWatch Agent user to docker group (only if Docker is installed)
  user:
    name: cwagent
    groups: docker
    append: yes
  when: docker_check.rc == 0

- name: Enable CloudWatch Agent service
  systemd:
    name: amazon-cloudwatch-agent
    enabled: yes
    state: restarted

- name: Start CloudWatch Agent
  command: >
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config
    -m ec2
    -s
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json